services:
  # Django application
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./media:/app/media  # Ensure media folder is mapped
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=imagewebsite
      - DB_USER=imagewebsite_user
      - DB_PASSWORD=imagewebsite2024!

  # PostgreSQL database
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=imagewebsite
      - POSTGRES_USER=imagewebsite_user
      - POSTGRES_PASSWORD=imagewebsite2024!
    ports:
      - "5432:5432"

volumes:
  postgres_data:
